services:
  - type: web
    name: ecfr-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    workingDir: backend
    autoDeploy: true

  - type: web
    name: ecfr-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview -- --port 3000"
    workingDir: frontend
    staticPublishPath: dist
    autoDeploy: true
